### ISSUE TITLE
Check files before commit

### ISSUE THREAD

**Issue by extsoft** [extsoft/elegant-git#12]
Command:
```bash
git elegant check
```
Base:
- `git diff --check` allows to check unstaged files
- `git diff --cached --check`allows to check staged files

Logic: 
- [x] by default, unstaged and staged changes has to be tested (`-a` or `--all` option)
- [x]  `-u` or `--unstaged` option runs the check for unstaged changes
- [x] `-s` or `--staged` option runs the check for staged changes
- [x] make sure autocompletion works for `--unstaged` and `--staged` and `--all` options.

**Comment by ivan-podorozhnyi** [comment]
@extsoft Is there any sense in `-a` and `--all` flags?
Do you mean by saying:
> Logic:
 by default, unstaged and staged changes has to be tested (-a or --all option)

that all other arguments passed including `-a` and `--all` flags have to check both staged and unstaged files?

**Comment by extsoft** [comment]
@ivan-podorozhnyi if
- no arguments - the command behaves like `--all` argument
- `--all` argument  - the command checks staged and unstaged changes
- ...

Is it better now?

**Comment by ivan-podorozhnyi** [comment]
@extsoft clear, thanks!
