### ISSUE TITLE
Add unit tests for 'clone' command

### ISSUE THREAD

**Issue by extsoft** [extsoft/elegant-git#18]
Please create tests only for positive flows.

**Comment by ivan-podorozhnyi** [comment]
@extsoft I want to write 0 exit code unit test for `clone` command but I got a problem with 
`cd $(basename -s .git $1)` command call inside it. Is there any special way to mock it?

**Comment by extsoft** [comment]
@ivan-podorozhnyi I'm not sure you have to mock `basename`. 
```bash
$ basename -s .git ffff/ddd/aaa.git
aaa
```
The above example demonstrates that you might have to mock `cd aaa` instead of `basename`.
