### ISSUE TITLE
Fix logic of _validate()

### ISSUE THREAD

**Issue by ivan-podorozhnyi** [extsoft/elegant-git#24]
`_validate()` method has a very strange logic. At first it checks whether first argument of the function is empty.  And then if prints a message: 'Specify branch name' is not set.
We need to change the logic of this method or possibly just change the string output to make some sense.

**Comment by extsoft** [comment]
I would suggest 
1. reviewing all calls of the `_validate`. For instance,
 ` _validate "$1" "Specify branch name"` update with ` _validate "$1" "branch name"`.
2. removing spare quotes (sample output has to be `branch name is not set`).

@ivan-podorozhnyi what do you think?

**Comment by ivan-podorozhnyi** [comment]
@extsoft It's a good idea. I will solve this issue after my first priority tasks.

**Comment by extsoft** [comment]
@ivan-podorozhnyi on more idea. We can even replace `_validate`with `${VAR_NAME?"Error message"}`. But this only checks is variable set or not.
```bash
$ dd=""
$ echo ${dd?dddd}

$ unset dd
$ echo ${dd?dddd}
-bash: dd: dddd
```

**Comment by ivan-podorozhnyi** [comment]
@extsoft I think both ways are ok. But I tried to change the color of output with `${d?"${__red}$"error message"${__reset}"}` and it doesn't work. So I suggest to keep our `_validate` function because this way `__rm`function works properly.

**Comment by extsoft** [comment]
@ivan-podorozhnyi okay.
