### ISSUE TITLE
Add aliases for all elegant git executables

### ISSUE THREAD

**Issue by extsoft** [extsoft/elegant-git#29]
Using [git aliases](https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases), need to configure shortcuts in the following format: 

`git elegant push` is equivalent to `git epush` - use prefix `e` before the command.

The aliases have to be generated on the fly based on available commands.

**Comment by AntonKarabaza** [comment]
@extsoft Please, clarify what you mean by "generate on the fly"? I suggest to put aliases configuration to `git-elegant-configure`.
