### ISSUE TITLE
git-elegant:169-170: Remove commands loading from main...

### ISSUE THREAD

**Issue by 0pdd** [extsoft/elegant-git#31]
The puzzle `6-228df600` (from #6) in [`src/main/git-elegant`](https://github.com/extsoft/elegant-git/blob/master/src/main/git-elegant) (lines 169-170) has to be resolved: "Remove commands loading from main executable. It will be possible when all commands will be migrated to separate executables."

The puzzle was created by Dmytro Serdiuk on 22-Aug-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by extsoft** [comment]
@ivan-podorozhnyi please create separate issues and link to this issue as dependencies.

**Comment by ivan-podorozhnyi** [comment]
@extsoft Done.
