### ISSUE TITLE
Move changes from current to new branch

### ISSUE THREAD

**Issue by extsoft** [extsoft/elegant-git#32]
Problem:
- make some changes
- call `git elegant feature xxx`
- error: `Your index contains uncommitted changes.`

Solution:
- create a stash (`git stash`) if there are some changed
-  remove the stash after moving to the new branch (`git stash pop`)

Add unit tests to verify positive and negative cases.

**Comment by ivan-podorozhnyi** [comment]
@extsoft can you reproduce it?
My output:
```
$ git elegant feature new_branch
M       new
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
M       new
Switched to a new branch 'new_branch'
```

**Comment by extsoft** [comment]
@ivan-podorozhnyi Possible scenario:
1. make some changes in `master`
2. run `git elegant feature xxx`

Is it working now?

**Comment by ivan-podorozhnyi** [comment]
@extsoft now it's not. Understood the idea.

**Comment by extsoft** [comment]
@ivan-podorozhnyi changes can be stashed or not.
