### ISSUE TITLE
Configure whitespaces

### ISSUE THREAD

**Issue by extsoft** [extsoft/elegant-git#58]
https://stackoverflow.com/questions/3372822/git-trim-whitespace?answertab=active#tab-top

Ask a user to apply this configuration:
```
[core]
    whitespace = trailing-space,space-before-tab
[apply]
    whitespace = fix
```
DoD:
1. Must be present in local and global config.
2. Use defaults from the sample above if git's global config has no values. 
3. Ask a user "configure whitespaces?" and apply configuration on if the user will agree

**Comment by AntonKarabaza** [comment]
@extsoft From [Git Documentation](https://git-scm.com/docs/git-config#git-config-corewhitespace):
> `space-before-tab` (enabled by default)
> `trailing-space` is a short-hand to cover both `blank-at-eol` and `blank-at-eof`
> `blank-at-eol` (enabled by default)
> `blank-at-eof` (enabled by default)

Seems, that we don't need to configure:
```
[core]
    whitespace = trailing-space,space-before-tab
```
