### ISSUE TITLE
Move 'pull' command to separate executable

### ISSUE THREAD

**Issue by extsoft** [extsoft/elegant-git#7]
`pull` command has to

- `git pull` for current branch if no args were passed
- checkout passed branch and then pull it  if an arg was passed

Look for #26 as for an example.

**Comment by ivan-podorozhnyi** [comment]
@extsoft do we have to keep `git fetch --tags` call inside this command?

**Comment by extsoft** [comment]
@ivan-podorozhnyi I added new issue #47 to discuss this. You can write your opinion here. In this task,   do not change the functionally.

**Comment by ivan-podorozhnyi** [comment]
@extsoft I need your advice. My solution looks bad but I have no other ideas. What do you think?

git-elegant
```
clear-local() {
    . "$BINS/git-elegant-pull"
    default $MASTER
    #the rest of this command
}
```

git-elegant-pull
```
#!/usr/bin/env bash
set -e

default() {
    if [ -n "$1" ]; then
        git checkout "$1"
    fi
    git fetch --tags
    git pull
}
```

**Comment by extsoft** [comment]
@ivan-podorozhnyi 
```bash
clear-local() {
    git elegant pull $MASTER
    #the rest of this command
}
```
Is it better?

**Comment by ivan-podorozhnyi** [comment]
@extsoft Thanks for idea, but it doesn't work.
```
clear-local() {
    main pull $MASTER
    #the rest of this command
}
```
This works and looks not bad.

**Comment by extsoft** [comment]
@ivan-podorozhnyi could you please show your function and unit test?

**Comment by ivan-podorozhnyi** [comment]
Function inside git-elegant:
```
clear-local() {
    git elegant pull $MASTER
    local cmd="git branch -lvv | grep gone | awk {'print \$1'}"
    __loop "git branch -d" $(eval "$cmd") || \
        (
            __gm "There are unmerged branches:" && \
            __loop "__gm -" $(eval "$cmd") && \
            __batch "Do you want to delete all unmerged branches?" "Delete this?" "git branch -D" $(eval "$cmd")
        )
}
```

Function inside git-elegant-pull:
```
#!/usr/bin/env bash
set -e

default() {
    if [ -n "$1" ]; then
        git checkout "$1"
    fi
    git fetch --tags
    git pull
}
```
Unit test:
```
#!/usr/bin/env bats -ex

load commons
load fake-read

setup() {
    fake-pass git "branch -lvv" "first [gone]"
    fake-pass git "checkout master"
    fake-pass git "fetch --tags"
    fake-pass git pull
    fake-pass git "branch -d first"
}

@test "exit code is 0 when run 'git-elegant clear-local'" {
  run git-elegant clear-local
  [ "$status" -eq 0 ]
}
```

**Comment by extsoft** [comment]
@ivan-podorozhnyi and what is the problem?

**Comment by ivan-podorozhnyi** [comment]
@extsoft the problem is that unit test fails with `git elegant pull $MASTER` but works fine with `main pull $MASTER`. 
I tried to use debug while running tests but bat's debug mode looks very strange and not clear for me.

**Comment by ivan-podorozhnyi** [comment]
@extsoft found the reason! Command `git-elegant pull $MASTER` is correct.
