### ISSUE TITLE
Update starting lines with "|"

### ISSUE THREAD

**Issue by extsoft** [extsoft/elegant-git#9]
`git config core.commentChar "|"`
https://stackoverflow.com/questions/2788092/start-a-git-commit-message-with-a-hashmark

This configuration has to appears in global configuration and repo configuration.

**Comment by extsoft** [comment]
`# ; @ ! $ % ^ & | :` - a list of options.

**Comment by 0pdd** [comment]
@extsoft the puzzle [#117](https://github.com/bees-hive/elegant-git/issues/117) is still not solved.

**Comment by 0pdd** [comment]
@extsoft the only puzzle [#117](https://github.com/bees-hive/elegant-git/issues/117) is solved here.
